set(SRC_FILES
    AppStart.cpp
    AppUpdate.cpp
    AppCamera.cpp
    AppGameplay.cpp
    AppEnd.cpp
    AnimatedCharacter.cpp
    LawnMowerSystem.cpp
    Plant.cpp
    PlantCatalog.cpp
    PlantFactory.cpp
    ProjectileSystem.cpp
    Sun.cpp
    SunSystem.cpp
    ZombieFactory.cpp
    ZombieSpawner.cpp
)

set(INCLUDE_FILES
    App.hpp
    AnimatedCharacter.hpp
    Background.hpp
    Bullet.hpp
    GridSystem.hpp
    LawnMower.hpp
    LawnMowerSystem.hpp
    BucketZombie.hpp
    ConeheadZombie.hpp
    FlagZombie.hpp
    NormalZombie.hpp
    PlantAction.hpp
    PlantCatalog.hpp
    PlantFactory.hpp
    PlantGrid.hpp
    Plant.hpp
    Peashooter.hpp
    IceShooter.hpp
    FastShooter.hpp
    Sunflower.hpp
    Wallnut.hpp
    PotatoMine.hpp
    CherryBomb.hpp
    Chomper.hpp
    LevelConfig.hpp
    Zombie.hpp
    ZombieFactory.hpp
    ZombieSpawner.hpp
    StatusEffect.hpp
    ZombieCorpse.hpp
    ProjectileSystem.hpp
    Sun.hpp
    SunSystem.hpp
    SunCounter.hpp
    CardSlot.hpp
)

set(TEST_FILES
)
