set(SRC_FILES
    AppStart.cpp
    AppUpdate.cpp
    AppCamera.cpp
    AppGameplay.cpp
    AppEnd.cpp
    AnimatedCharacter.cpp
    Sun.cpp
)

set(INCLUDE_FILES
    App.hpp
    AnimatedCharacter.hpp
    Background.hpp
    Bullet.hpp
    GridSystem.hpp
    LawnMower.hpp
    BucketZombie.hpp
    ConeheadZombie.hpp
    FlagZombie.hpp
    NormalZombie.hpp
    Plant.hpp
    Peashooter.hpp
    IceShooter.hpp
    FastShooter.hpp
    Sunflower.hpp
    Wallnut.hpp
    Zombie.hpp
    StatusEffect.hpp
    ZombieCorpse.hpp
    Sun.hpp
    SunCounter.hpp
    CardSlot.hpp
)

set(TEST_FILES
)
