set(SRC_FILES
    app/AppStart.cpp
    app/AppUpdate.cpp
    app/AppCheats.cpp
    app/AppCamera.cpp
    app/AppGameplay.cpp
    app/AppEnd.cpp
    core/AnimatedCharacter.cpp
    systems/LawnMowerSystem.cpp
    entities/Plant.cpp
    catalog/PlantCatalog.cpp
    factory/PlantFactory.cpp
    systems/ProjectileSystem.cpp
    entities/Sun.cpp
    systems/SunSystem.cpp
    factory/ZombieFactory.cpp
    systems/ZombieSpawner.cpp
)

set(INCLUDE_FILES
    app/App.hpp
    core/AnimatedCharacter.hpp
    ui/Background.hpp
    entities/Bullet.hpp
    core/GridSystem.hpp
    entities/LawnMower.hpp
    systems/LawnMowerSystem.hpp
    zombies/BucketZombie.hpp
    zombies/ConeheadZombie.hpp
    zombies/FlagZombie.hpp
    zombies/NormalZombie.hpp
    catalog/PlantAction.hpp
    catalog/PlantCatalog.hpp
    factory/PlantFactory.hpp
    systems/PlantGrid.hpp
    entities/Plant.hpp
    plants/Peashooter.hpp
    plants/IceShooter.hpp
    plants/FastShooter.hpp
    plants/Sunflower.hpp
    plants/Wallnut.hpp
    plants/PotatoMine.hpp
    plants/CherryBomb.hpp
    plants/Chomper.hpp
    config/LevelConfig.hpp
    entities/Zombie.hpp
    factory/ZombieFactory.hpp
    systems/ZombieSpawner.hpp
    systems/StatusEffect.hpp
    entities/ZombieCorpse.hpp
    systems/ProjectileSystem.hpp
    entities/Sun.hpp
    systems/SunSystem.hpp
    ui/SunCounter.hpp
    ui/CardSlot.hpp
)

set(TEST_FILES
)
